apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testcluster-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.hosts }}
      secretName: testcluster-tls
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rentcar.appName }}
                port:
                  number: 80
